# Generated by Django 6.0.4 on 2026-04-23 16:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0005_relay_provider_to_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('oid', models.CharField(max_length=255, null=True, unique=True)),
                ('resource_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='gatewayaction',
            name='gateway',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='gateway.gateway'),
        ),
        migrations.AddField(
            model_name='relay',
            name='gateway',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relays', to='gateway.gateway'),
        ),
    ]
