# Generated by Django 6.0.4 on 2026-04-27 13:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom', '0007_series_repeat_count_series_repeat_reasons_and_more'),
        ('users', '__first__'),
        ('users', '__first__'),
        ('users', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_size', models.IntegerField()),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reading_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opinion', models.CharField(choices=[('NORMAL', 'Normal'), ('TECHNICAL_RECALL', 'Technical recall'), ('RECALL', 'Recall for assessment')])),
                ('additional_details', models.TextField(blank=True, default='')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opinions', to='dicom.study')),
            ],
            options={
                'unique_together': {('study', 'reader')},
            },
        ),
        migrations.CreateModel(
            name='RecallForAssessmentDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('right_breast_opinion', models.CharField(choices=[('NORMAL', 'Normal'), ('ABNORMAL', 'Abnormal, recall for assessment')])),
                ('right_breast_comment', models.CharField(blank=True, default='')),
                ('left_breast_opinion', models.CharField(choices=[('NORMAL', 'Normal'), ('ABNORMAL', 'Abnormal, recall for assessment')])),
                ('left_breast_comment', models.CharField(blank=True, default='')),
                ('reading', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recall_for_assessment_details', to='dicom.reading')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RetakeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retake_requests', to='dicom.reading')),
                ('laterality', models.CharField(choices=[('L', 'L'), ('R', 'R')])),
                ('view_position', models.CharField(choices=[('CC', 'Cc'), ('MLO', 'Mlo')])),
            ],
            options={
                'unique_together': {('reading', 'view_position', 'laterality')},
            },
        ),
        migrations.CreateModel(
            name='ReadingSessionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dicom.readingsession')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reading_session_items', to='dicom.study')),
                ('reading', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reading_session_item', to='dicom.reading')),
            ],
            options={
                'unique_together': {('session', 'order')},
            },
        ),
    ]
