# Generated by Django 6.0.4 on 2026-04-27 14:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def set_appointment(apps, schema_editor):
    Study = apps.get_model('dicom', 'Study')
    Appointment = apps.get_model('participants', 'Appointment')
    GatewayAction = apps.get_model('gateway', 'GatewayAction')
    for study in Study.objects.all():
        if study.source_message_id:
            action = GatewayAction.objects.filter(id=study.source_message_id).first()
            if action is None and settings.DJANGO_ENV != 'production':
                # workaround inconsistent demo data by linking orphan studies to arbitrary appointments
                study.appointment = Appointment.objects.filter(dicom_study=None).first()
            else:
                study.appointment = action.appointment
            study.save()

def unset_appointment(apps, schema_editor):
    Study = apps.get_model('dicom', 'Study')
    Study.objects.all().update(appointment=None)

class Migration(migrations.Migration):

    dependencies = [
        ('dicom', '0008_readingsession_reading_recallforassessmentdetails_and_more'),
        ('participants', '0001_squashed_0067_participantreportedmammogram_created_by_and_more'),
        ('gateway', '0005_relay_provider_to_setting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readingsessionitem',
            old_name='order',
            new_name='reading_order',
        ),
        migrations.AlterUniqueTogether(
            name='readingsessionitem',
            unique_together={('session', 'reading_order')},
        ),
        migrations.AddField(
            model_name='study',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='study',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='study',
            name='appointment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dicom_study', to='participants.appointment'),
        ),
        migrations.RunPython(code=set_appointment, reverse_code=unset_appointment),
        migrations.AlterField(
            model_name='study',
            name='appointment',
            field=models.OneToOneField(
                to='participants.Appointment', on_delete=models.PROTECT, related_name="dicom_study"
            )
        )
    ]
