# Generated by Django 6.0.4 on 2026-04-30 12:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom', '0009_rename_order_readingsessionitem_reading_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='dicom.study')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunSQL(
            sql='TRUNCATE TABLE dicom_readingsession CASCADE',
            reverse_sql='TRUNCATE table dicom_readingsession CASCADE',
        ),
        migrations.AlterField(
            model_name='reading',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='dicom.study'),
        ),
        migrations.RemoveField(
            model_name='readingsessionitem',
            name='reading',
        ),
        migrations.RemoveField(
            model_name='readingsessionitem',
            name='study',
        ),
        migrations.AddField(
            model_name='readingsessionitem',
            name='case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reading_session_item', to='dicom.case'),
            preserve_default=False,
        )
    ]
