DEPLOYED_TO: dev
BASE_URL: https://dev.manage-breast-screening.non-live.screening.nhs.uk
BASIC_AUTH_ENABLED: True
CIS2_SERVER_METADATA_URL: https://am.nhsint.auth-ptl.cis2.spineservices.nhs.uk/openam/oauth2/realms/root/realms/NHSIdentity/realms/Healthcare/.well-known/openid-configuration
PERSONAS_ENABLED: 1
CSRF_TRUSTED_ORIGINS: 'https://dev.manage-breast-screening.non-live.screening.nhs.uk'
APPLICATIONINSIGHTS_IS_ENABLED: True
GUNICORN_WORKER_CONNECTIONS: 50 #reduce in dev as we have small PG instance
