from django.urls import path
from django.views.decorators.http import require_http_methods

from manage_breast_screening.mammograms.views import (
    mammogram_views,
    update_breast_features_view,
)
from manage_breast_screening.mammograms.views.other_information import (
    hormone_replacement_therapy_views,
    other_medical_information_views,
    pregnancy_and_breastfeeding_views,
)

from .views import (
    add_multiple_images_information_view,
    appointment_note_views,
    appointment_workflow_views,
    image_details_views,
    participant_reported_mammogram_views,
    show_appointment_views,
    special_appointment_views,
    symptom_views,
)
from .views.medical_history import (
    benign_lump_history_item_views,
    breast_augmentation_history_item_views,
    breast_cancer_history_item_views,
    cyst_history_item_views,
    implanted_medical_device_history_item_views,
    mastectomy_or_lumpectomy_history_item_views,
    other_procedure_history_item_views,
)

app_name = "mammograms"


@require_http_methods(["GET"])
def not_implemented_view(request, pk):
    raise NotImplementedError()


urlpatterns = [
    path(
        "<uuid:pk>/check-in/",
        appointment_workflow_views.check_in,
        name="check_in",
    ),
    path(
        "<uuid:pk>/start-appointment/",
        appointment_workflow_views.start_appointment,
        name="start_appointment",
    ),
    path(
        "<uuid:pk>/pause-appointment/",
        appointment_workflow_views.PauseAppointment.as_view(),
        name="pause_appointment",
    ),
    path(
        "<uuid:pk>/resume-appointment/",
        appointment_workflow_views.resume_appointment,
        name="resume_appointment",
    ),
    path(
        "<uuid:pk>/",
        show_appointment_views.ShowAppointment.as_view(),
        name="show_appointment",
    ),
    path(
        "<uuid:pk>/participant/",
        show_appointment_views.ParticipantDetails.as_view(),
        name="participant_details",
    ),
    path(
        "<uuid:pk>/images/",
        show_appointment_views.ImageDetails.as_view(),
        name="appointment_image_details",
    ),
    path(
        "<uuid:pk>/medical-information/",
        show_appointment_views.MedicalInformation.as_view(),
        name="medical_information",
    ),
    path(
        "<uuid:pk>/note/",
        appointment_note_views.AppointmentNoteView.as_view(),
        name="appointment_note",
    ),
    path(
        "<uuid:pk>/note-review/",
        appointment_note_views.AppointmentNoteReviewView.as_view(),
        name="appointment_note_review",
    ),
    path(
        "<uuid:pk>/note/delete/",
        appointment_note_views.DeleteAppointmentNoteView.as_view(),
        name="delete_appointment_note",
    ),
    path(
        "<uuid:pk>/confirm-identity/",
        appointment_workflow_views.ConfirmIdentity.as_view(),
        name="confirm_identity",
    ),
    path(
        "<uuid:pk>/record-medical-information/",
        appointment_workflow_views.RecordMedicalInformation.as_view(),
        name="record_medical_information",
    ),
    path(
        "<uuid:pk>/record-medical-information/mark-reviewed/<str:section>/",
        appointment_workflow_views.MarkSectionReviewed.as_view(),
        name="mark_section_reviewed",
    ),
    path(
        "<uuid:pk>/take-images/",
        appointment_workflow_views.TakeImages.as_view(),
        name="take_images",
    ),
    path(
        "<uuid:pk>/gateway-images/",
        appointment_workflow_views.GatewayImages.as_view(),
        name="gateway_images",
    ),
    path(
        "<uuid:pk>/cannot-go-ahead/",
        appointment_workflow_views.AppointmentCannotGoAhead.as_view(),
        name="appointment_cannot_go_ahead",
    ),
    path(
        "<uuid:pk>/special-appointment/",
        special_appointment_views.ProvideSpecialAppointmentDetails.as_view(),
        name="provide_special_appointment_details",
    ),
    path(
        "<uuid:pk>/record-medical-information/lump/",
        symptom_views.AddLumpView.as_view(),
        name="add_symptom_lump",
    ),
    path(
        "<uuid:pk>/record-medical-information/lump/<uuid:symptom_pk>/",
        symptom_views.ChangeLumpView.as_view(),
        name="change_symptom_lump",
    ),
    path(
        "<uuid:pk>/record-medical-information/swelling-or-shape-change/",
        symptom_views.AddSwellingOrShapeChangeView.as_view(),
        name="add_symptom_swelling_or_shape_change",
    ),
    path(
        "<uuid:pk>/record-medical-information/swelling-or-shape-change/<uuid:symptom_pk>/",
        symptom_views.ChangeSwellingOrShapeChangeView.as_view(),
        name="change_symptom_swelling_or_shape_change",
    ),
    path(
        "<uuid:pk>/record-medical-information/skin-change/",
        symptom_views.AddSkinChangeView.as_view(),
        name="add_symptom_skin_change",
    ),
    path(
        "<uuid:pk>/record-medical-information/skin-change/<uuid:symptom_pk>/",
        symptom_views.ChangeSkinChangeView.as_view(),
        name="change_symptom_skin_change",
    ),
    path(
        "<uuid:pk>/record-medical-information/nipple-change/",
        symptom_views.AddNippleChangeView.as_view(),
        name="add_symptom_nipple_change",
    ),
    path(
        "<uuid:pk>/record-medical-information/nipple-change/<uuid:symptom_pk>/",
        symptom_views.ChangeNippleChangeView.as_view(),
        name="change_symptom_nipple_change",
    ),
    path(
        "<uuid:pk>/record-medical-information/breast-pain/",
        symptom_views.AddBreastPainView.as_view(),
        name="add_symptom_breast_pain",
    ),
    path(
        "<uuid:pk>/record-medical-information/breast-pain/<uuid:symptom_pk>/",
        symptom_views.ChangeBreastPainView.as_view(),
        name="change_symptom_breast_pain",
    ),
    path(
        "<uuid:pk>/record-medical-information/other/",
        symptom_views.AddOtherSymptomView.as_view(),
        name="add_symptom_other",
    ),
    path(
        "<uuid:pk>/record-medical-information/other/<uuid:symptom_pk>/",
        symptom_views.ChangeOtherSymptomView.as_view(),
        name="change_symptom_other",
    ),
    path(
        "<uuid:pk>/record-medical-information/delete_symptom/<uuid:symptom_pk>/",
        symptom_views.DeleteSymptomView.as_view(),
        name="delete_symptom",
    ),
    path(
        "<uuid:pk>/record-medical-information/breast-cancer-history/",
        breast_cancer_history_item_views.AddBreastCancerHistoryView.as_view(),
        name="add_breast_cancer_history_item",
    ),
    path(
        "<uuid:pk>/record-medical-information/breast-cancer-history/<uuid:history_item_pk>/",
        breast_cancer_history_item_views.UpdateBreastCancerHistoryView.as_view(),
        name="change_breast_cancer_history_item",
    ),
    path(
        "<uuid:pk>/record-medical-information/breast-cancer-history/<uuid:history_item_pk>/delete/",
        breast_cancer_history_item_views.DeleteBreastCancerHistoryView.as_view(),
        name="delete_breast_cancer_history_item",
    ),
    path(
        "<uuid:pk>/record-medical-information/implanted-medical-device-history/",
        implanted_medical_device_history_item_views.AddImplantedMedicalDeviceHistoryView.as_view(),
        name="add_implanted_medical_device_history_item",
    ),
    path(
        "<uuid:pk>/record-medical-information/implanted-medical-device-history/<uuid:history_item_pk>/",
        implanted_medical_device_history_item_views.UpdateImplantedMedicalDeviceHistoryView.as_view(),
        name="change_implanted_medical_device_history_item",
    ),
    path(
        "<uuid:pk>/record-medical-information/implanted-medical-device-history/<uuid:history_item_pk>/delete/",
        implanted_medical_device_history_item_views.DeleteImplantedMedicalDeviceHistoryView.as_view(),
        name="delete_implanted_medical_device_history_item",
    ),
    path(
        "<uuid:pk>/record-medical-information/cyst-history/",
        cyst_history_item_views.AddCystHistoryView.as_view(),
        name="add_cyst_history_item",
    ),
    path(
        "<uuid:pk>/record-medical-information/cyst-history/<uuid:history_item_pk>/",
        cyst_history_item_views.UpdateCystHistoryView.as_view(),
        name="change_cyst_history_item",
    ),
    path(
        "<uuid:pk>/record-medical-information/cyst-history/<uuid:history_item_pk>/delete/",
        cyst_history_item_views.DeleteCystHistoryView.as_view(),
        name="delete_cyst_history_item",
    ),
    path(
        "<uuid:pk>/record-medical-information/breast-augmentation-history/",
        breast_augmentation_history_item_views.AddBreastAugmentationHistoryView.as_view(),
        name="add_breast_augmentation_history_item",
    ),
    path(
        "<uuid:pk>/record-medical-information/breast-augmentation-history/<uuid:history_item_pk>/",
        breast_augmentation_history_item_views.UpdateBreastAugmentationHistoryView.as_view(),
        name="change_breast_augmentation_history_item",
    ),
    path(
        "<uuid:pk>/record-medical-information/breast-augmentation-history/<uuid:history_item_pk>/delete/",
        breast_augmentation_history_item_views.DeleteBreastAugmentationHistoryView.as_view(),
        name="delete_breast_augmentation_history_item",
    ),
    path(
        "<uuid:pk>/record-medical-information/benign-lump-history/",
        benign_lump_history_item_views.AddBenignLumpHistoryItemView.as_view(),
        name="add_benign_lump_history_item",
    ),
    path(
        "<uuid:pk>/record-medical-information/benign-lump-history/<uuid:history_item_pk>/",
        benign_lump_history_item_views.UpdateBenignLumpHistoryItemView.as_view(),
        name="change_benign_lump_history_item",
    ),
    path(
        "<uuid:pk>/record-medical-information/benign-lump-history/<uuid:history_item_pk>/delete/",
        benign_lump_history_item_views.DeleteBenignLumpHistoryItemView.as_view(),
        name="delete_benign_lump_history_item",
    ),
    path(
        "<uuid:pk>/record-medical-information/mastectomy-or-lumpectomy-history/",
        mastectomy_or_lumpectomy_history_item_views.AddMastectomyOrLumpectomyHistoryView.as_view(),
        name="add_mastectomy_or_lumpectomy_history_item",
    ),
    path(
        "<uuid:pk>/record-medical-information/mastectomy-or-lumpectomy-history/<uuid:history_item_pk>/",
        mastectomy_or_lumpectomy_history_item_views.UpdateMastectomyOrLumpectomyHistoryView.as_view(),
        name="change_mastectomy_or_lumpectomy_history_item",
    ),
    path(
        "<uuid:pk>/record-medical-information/mastectomy-or-lumpectomy-history/<uuid:history_item_pk>/delete/",
        mastectomy_or_lumpectomy_history_item_views.DeleteMastectomyOrLumpectomyHistoryView.as_view(),
        name="delete_mastectomy_or_lumpectomy_history_item",
    ),
    path(
        "<uuid:pk>/record-medical-information/other-procedure-history/",
        other_procedure_history_item_views.AddOtherProcedureHistoryView.as_view(),
        name="add_other_procedure_history_item",
    ),
    path(
        "<uuid:pk>/record-medical-information/other-procedure-history/<uuid:history_item_pk>/",
        other_procedure_history_item_views.UpdateOtherProcedureHistoryView.as_view(),
        name="change_other_procedure_history_item",
    ),
    path(
        "<uuid:pk>/record-medical-information/other-procedure-history/<uuid:history_item_pk>/delete/",
        other_procedure_history_item_views.DeleteOtherProcedureHistoryView.as_view(),
        name="delete_other_procedure_history_item",
    ),
    path(
        "<uuid:pk>/record-medical-information/breast-features/update/",
        update_breast_features_view.UpdateBreastFeaturesView.as_view(),
        name="update_breast_features",
    ),
    path(
        "<uuid:pk>/previous-mammograms/add",
        participant_reported_mammogram_views.AddParticipantReportedMammogramView.as_view(),
        name="add_previous_mammogram",
    ),
    path(
        "<uuid:pk>/previous-mammograms/<uuid:participant_reported_mammogram_pk>",
        participant_reported_mammogram_views.UpdateParticipantReportedMammogramView.as_view(),
        name="change_previous_mammogram",
    ),
    path(
        "<uuid:pk>/previous-mammograms/<uuid:participant_reported_mammogram_pk>/delete/",
        participant_reported_mammogram_views.DeleteParticipantReportedMammogramView.as_view(),
        name="delete_previous_mammogram",
    ),
    path(
        "<uuid:appointment_pk>/appointment-should-not-proceed/<uuid:participant_reported_mammogram_pk>",
        mammogram_views.appointment_should_not_proceed,
        name="appointment_should_not_proceed",
    ),
    path(
        "<uuid:pk>/proceed_anyway/<uuid:participant_reported_mammogram_pk>",
        mammogram_views.AppointmentProceedAnywayView.as_view(),
        name="proceed_anyway",
    ),
    path(
        "<uuid:appointment_pk>/attended-not-screened/",
        mammogram_views.attended_not_screened,
        name="attended_not_screened",
    ),
    path(
        "<uuid:pk>/check-information/",
        appointment_workflow_views.CheckInformation.as_view(),
        name="check_information",
    ),
    path(
        "<uuid:pk>/image-details/new/",
        image_details_views.AddImageDetailsView.as_view(),
        name="add_image_details",
    ),
    path(
        "<uuid:pk>/image-details/update/",
        image_details_views.UpdateImageDetailsView.as_view(),
        name="update_image_details",
    ),
    path(
        "<uuid:pk>/multiple-images-information/add",
        add_multiple_images_information_view.AddMultipleImagesInformationView.as_view(),
        name="add_multiple_images_information",
    ),
    path(
        "<uuid:pk>/images/stream",
        appointment_workflow_views.appointment_images_stream,
        name="appointment_images_stream",
    ),
    path(
        "<uuid:pk>/record-medical-information/hormone-replacement-therapy/",
        hormone_replacement_therapy_views.AddHormoneReplacementTherapyView.as_view(),
        name="add_hormone_replacement_therapy",
    ),
    path(
        "<uuid:pk>/record-medical-information/hormone-replacement-therapy/update/",
        hormone_replacement_therapy_views.UpdateHormoneReplacementTherapyView.as_view(),
        name="change_hormone_replacement_therapy",
    ),
    path(
        "<uuid:pk>/record-medical-information/pregnancy-and-breastfeeding/",
        pregnancy_and_breastfeeding_views.AddPregnancyAndBreastfeedingView.as_view(),
        name="add_pregnancy_and_breastfeeding",
    ),
    path(
        "<uuid:pk>/record-medical-information/pregnancy-and-breastfeeding/update/",
        pregnancy_and_breastfeeding_views.UpdatePregnancyAndBreastfeedingView.as_view(),
        name="change_pregnancy_and_breastfeeding",
    ),
    path(
        "<uuid:pk>/record-medical-information/other-medical-information/",
        other_medical_information_views.AddOtherMedicalInformationView.as_view(),
        name="add_other_medical_information",
    ),
    path(
        "<uuid:pk>/record-medical-information/other-medical-information/update/",
        other_medical_information_views.UpdateOtherMedicalInformationView.as_view(),
        name="change_other_medical_information",
    ),
    path(
        "<uuid:pk>/record-medical-information/other-medical-information/delete/",
        other_medical_information_views.DeleteOtherMedicalInformationView.as_view(),
        name="delete_other_medical_information",
    ),
]
