from django.urls import path

from .views import (
    appointment_views,
    medical_history_views,
    special_appointment_views,
    symptom_views,
)

app_name = "mammograms"

urlpatterns = [
    path(
        "<uuid:pk>/check-in/",
        appointment_views.check_in,
        name="check_in",
    ),
    path(
        "<uuid:pk>/start-appointment/",
        appointment_views.start_appointment,
        name="start_appointment",
    ),
    path(
        "<uuid:pk>/",
        appointment_views.ShowAppointment.as_view(),
        name="show_appointment",
    ),
    path(
        "<uuid:pk>/participant/",
        appointment_views.ParticipantDetails.as_view(),
        name="participant_details",
    ),
    path(
        "<uuid:pk>/confirm-identity/",
        appointment_views.ConfirmIdentity.as_view(),
        name="confirm_identity",
    ),
    path(
        "<uuid:pk>/ask-for-medical-information/",
        appointment_views.AskForMedicalInformation.as_view(),
        name="ask_for_medical_information",
    ),
    path(
        "<uuid:pk>/record-medical-information/",
        appointment_views.RecordMedicalInformation.as_view(),
        name="record_medical_information",
    ),
    path(
        "<uuid:pk>/awaiting-images/",
        appointment_views.AwaitingImages.as_view(),
        name="awaiting_images",
    ),
    path(
        "<uuid:pk>/cannot-go-ahead/",
        appointment_views.AppointmentCannotGoAhead.as_view(),
        name="appointment_cannot_go_ahead",
    ),
    path(
        "<uuid:pk>/special-appointment/",
        special_appointment_views.ProvideSpecialAppointmentDetails.as_view(),
        name="provide_special_appointment_details",
    ),
    path(
        "<uuid:pk>/special-appointment/which-reasons/",
        special_appointment_views.MarkReasonsTemporary.as_view(),
        name="mark_reasons_temporary",
    ),
    path(
        "<uuid:pk>/record-medical-information/lump/",
        symptom_views.AddLumpView.as_view(),
        name="add_symptom_lump",
    ),
    path(
        "<uuid:pk>/record-medical-information/lump/<uuid:symptom_pk>/",
        symptom_views.ChangeLumpView.as_view(),
        name="change_symptom_lump",
    ),
    path(
        "<uuid:pk>/record-medical-information/swelling-or-shape-change/",
        symptom_views.AddSwellingOrShapeChangeView.as_view(),
        name="add_symptom_swelling_or_shape_change",
    ),
    path(
        "<uuid:pk>/record-medical-information/swelling-or-shape-change/<uuid:symptom_pk>/",
        symptom_views.ChangeSwellingOrShapeChangeView.as_view(),
        name="change_symptom_swelling_or_shape_change",
    ),
    path(
        "<uuid:pk>/record-medical-information/skin-change/",
        symptom_views.AddSkinChangeView.as_view(),
        name="add_symptom_skin_change",
    ),
    path(
        "<uuid:pk>/record-medical-information/skin-change/<uuid:symptom_pk>/",
        symptom_views.ChangeSkinChangeView.as_view(),
        name="change_symptom_skin_change",
    ),
    path(
        "<uuid:pk>/record-medical-information/nipple-change/",
        symptom_views.AddNippleChangeView.as_view(),
        name="add_symptom_nipple_change",
    ),
    path(
        "<uuid:pk>/record-medical-information/nipple-change/<uuid:symptom_pk>/",
        symptom_views.ChangeNippleChangeView.as_view(),
        name="change_symptom_nipple_change",
    ),
    path(
        "<uuid:pk>/record-medical-information/other/",
        symptom_views.AddOtherSymptomView.as_view(),
        name="add_symptom_other",
    ),
    path(
        "<uuid:pk>/record-medical-information/other/<uuid:symptom_pk>/",
        symptom_views.ChangeOtherSymptomView.as_view(),
        name="change_symptom_other",
    ),
    path(
        "<uuid:pk>/record-medical-information/delete_symptom/<uuid:symptom_pk>/",
        symptom_views.DeleteSymptomView.as_view(),
        name="delete_symptom",
    ),
    path(
        "<uuid:pk>/record-medical-information/implanted_medical_device/",
        medical_history_views.AddImplantedMedicalDeviceView.as_view(),
        name="add_implanted_medical_device",
    ),
]
