# Generated by Django 5.2.3 on 2025-08-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_channelstatus_messagestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagebatch',
            name='notify_errors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messagebatch',
            name='status',
            field=models.CharField(choices=[('unscheduled', 'Unscheduled'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed_unrecoverable', 'Failed Unrecoverable'), ('failed_recoverable', 'Failed Recoverable')], default='unscheduled', max_length=50),
        ),
    ]
