# Generated by Django 5.2.7 on 2025-11-10 14:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0021_alter_clinic_code_clinic_notificatio_code_55dbdb_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extract',
            fields=[
                ('extract_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('sequence_number', models.IntegerField()),
                ('appointments', models.ManyToManyField(blank=True, to='notifications.appointment')),
            ],
        ),
    ]
