# Generated by Django 5.2.7 on 2025-11-10 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0022_extract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extract',
            old_name='extract_id',
            new_name='id',
        ),
    ]
