# Generated by Django 5.2.7 on 2025-11-10 11:41

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0034_breastcancerhistoryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreastAugmentationHistoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('right_breast_procedures', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BREAST_IMPLANTS', 'Breast implants (silicone or saline)'), ('OTHER_AUGMENTATION', 'Other augmentation'), ('NO_PROCEDURES', 'No procedures')]), default=list, size=None)),
                ('left_breast_procedures', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BREAST_IMPLANTS', 'Breast implants (silicone or saline)'), ('OTHER_AUGMENTATION', 'Other augmentation'), ('NO_PROCEDURES', 'No procedures')]), default=list, size=None)),
                ('procedure_year', models.IntegerField(null=True)),
                ('implants_have_been_removed', models.BooleanField(default=False)),
                ('additional_details', models.TextField(blank=True, default='')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breast_augmentation_history_items', to='participants.appointment')),
                ('removal_year', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
