# Generated by Django 5.2.7 on 2025-11-11 11:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0037_otherprocedurehistoryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CystHistoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('treatment', models.CharField(choices=[('DRAINAGE_OR_REMOVAL', 'Drainage or removal'), ('NO_TREATMENT', 'No treatment')])),
                ('additional_details', models.TextField(blank=True, default='')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cyst_history_items', to='participants.appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
