# Generated by Django 6.0.4 on 2026-04-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_squashed_0067_participantreportedmammogram_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='highlight_to_readers',
            field=models.BooleanField(default=True),
        ),
    ]
