name: 'Test stage'

on:
  workflow_call:
    inputs:
      build_datetime:
        description: 'Build datetime, set by the CI/CD pipeline workflow'
        required: true
        type: string
      build_timestamp:
        description: 'Build timestamp, set by the CI/CD pipeline workflow'
        required: true
        type: string
      build_epoch:
        description: 'Build epoch, set by the CI/CD pipeline workflow'
        required: true
        type: string
      nodejs_version:
        description: 'Node.js version, set by the CI/CD pipeline workflow'
        required: true
        type: string
      python_version:
        description: 'Python version, set by the CI/CD pipeline workflow'
        required: true
        type: string
      terraform_version:
        description: 'Terraform version, set by the CI/CD pipeline workflow'
        required: true
        type: string
      version:
        description: 'Version of the software, set by the CI/CD pipeline workflow'
        required: true
        type: string

jobs:
  test:
    name: 'Tests'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      frontend-changed: ${{ steps.path-changes.outputs.frontend == 'true' }}

    services:
      postgres:
        image: postgres:17.4-alpine3.21
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Detect specific kinds of code change by path
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4
        id: path-changes
        with:
          filters: |
            frontend:
              - 'manage_breast_screening/assets/**'
              - 'manage_breast_screening/auth/**'
              - 'manage_breast_screening/clinics/**'
              - 'manage_breast_screening/core/**'
              - 'manage_breast_screening/config/**'
              - 'manage_breast_screening/data/**'
              - 'manage_breast_screening/mammograms/**'
              - 'manage_breast_screening/nhsuk_forms/**'
              - 'manage_breast_screening/nonprod/**'
              - 'manage_breast_screening/participants/**'
              - 'manage_breast_screening/static/**'
              - 'manage_breast_screening/tests/system/**'

      - name: Set up uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
        with:
          enable-cache: true
          cache-dependency-glob: '**/uv.lock'

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: '${{inputs.python_version}}'

      - name: Install dependencies
        run: make dependencies

      - name: Check for missing migrations
        run: |
          if ! uv run manage.py makemigrations --check --dry-run; then
            echo "Error: makemigrations check failed! Failing build!"
            exit 1
          fi
        env:
          DATABASE_NAME: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_USER: postgres
          DATABASE_HOST: localhost

      - name: 'Run unit test suite'
        run: make test-unit ARGS="--doctest-modules"
        env:
          DATABASE_NAME: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_USER: postgres
          DATABASE_HOST: localhost

      - name: Test Report
        uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2
        if: ${{ !cancelled() }} # run this step even if previous step failed
        with:
          name: Report python unit tests
          path: reports/test-python-units.xml
          reporter: python-xunit

      - name: Report javascript unit tests
        uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2
        if: ${{ !cancelled() }} # run this step even if previous step failed
        with:
          name: Unit tests (javascript)
          path: reports/test-js-units.xml
          reporter: jest-junit

  frontend-integration-test:
    needs: test
    if: github.ref == 'refs/heads/main' || needs.test.outputs.frontend-changed == 'true'
    name: 'Frontend Tests'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    services:
      postgres:
        image: postgres:17.4-alpine3.21
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
        with:
          enable-cache: true
          cache-dependency-glob: '**/uv.lock'

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: '${{inputs.python_version}}'

      - name: Install dependencies
        run: make dependencies

      - name: Compile frontend assets
        run: npm run compile

      - name: Install Playwright browsers
        run: uv run playwright install chromium --with-deps --only-shell

      - name: 'Run Playwright system tests'
        run: make test-ui ARGS="--tracing on"
        env:
          DATABASE_NAME: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_USER: postgres
          DATABASE_HOST: localhost

      - name: Report UI tests
        uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2
        if: ${{ !cancelled() }} # run this step even if previous step failed
        with:
          name: UI tests
          path: reports/test-ui.xml
          reporter: python-xunit

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        if: ${{ !cancelled() }} # run this step even if previous step failed
        with:
          name: playwright-traces
          path: test-results/
          if-no-files-found: ignore
          retention-days: 7

  test-lint:
    name: 'Linting'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
        with:
          enable-cache: true
          cache-dependency-glob: '**/uv.lock'

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: '${{inputs.python_version}}'

      - name: Install dependencies
        run: make dependencies

      - name: Run linting
        run: make test-lint

      - name: Run ShellCheck
        run: find ./scripts -type f -name "*.sh" -exec shellcheck {} +

  perform-static-analysis:
    name: 'Perform static analysis'
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 5
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0 # Full history is needed to improving relevancy of reporting
      - name: 'Perform static analysis'
        uses: ./.github/actions/perform-static-analysis
        with:
          sonar_organisation_key: '${{ vars.SONAR_ORGANISATION_KEY }}'
          sonar_project_key: '${{ vars.SONAR_PROJECT_KEY }}'
          sonar_token: '${{ secrets.SONAR_TOKEN }}'
